resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.
    
    [active]
    demo-vm.OTUS.yc ansible_host=${yandex_compute_instance.instance.network_interface.0.nat_ip_address}


    DOC
  filename = "../ansible/inventory.yaml"

  depends_on = [
    yandex_compute_instance.instance
  ]
}
resource "null_resource" "wait" {
  provisioner "local-exec" {
    command = "sleep 15"
  }

  depends_on = [
    local_file.inventory
  ]
}
resource "null_resource" "ansible_nginx" {
  provisioner "local-exec" {
    command = "ansible-playbook -u ubuntu -i ../ansible/inventory.yaml ../ansible/nginx.yaml"
  }

  depends_on = [
    null_resource.wait
  ]
}
resource "null_resource" "check_result" {
  provisioner "local-exec" {
    command = "curl ${yandex_compute_instance.instance.network_interface.0.nat_ip_address}"
  }
  depends_on = [
    null_resource.ansible_nginx
  ]
}